# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b121a7eb19853b01d44f7649867ee299f077dfbedf3be0796b389d67732fc6b1d7b19897f2f23ca88fe30b21c24b3d318a29d84dca8f18183d816c355b20a4

test:
  secret_key_base: a6709342b84ce7d990b160af87231ba08aff381b6ec66053af8ea4add20a90a028de80df92a6df7cfd57c15b9a3ec6f39b828bfccf94eb5db34fe41a1ac063af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
